apiVersion: v1
kind: ConfigMap
metadata:
 name: fluentd-config
data:
 fluent.conf: |
  <source>
   @type tail
   format none
   path /var/log/input.log
   read_from_head true
   tag log.input
  </source>

  <match **>
   @type file
   path /var/log/output.*.log
   symlink_path /var/log/output.log
  </match>